os: linux
dist: xenial
language: python
python:
    - 3.7
env:
    - TOXENV=py37
install:
    - pip install -U pip
    - pip install tox
    - pip install coveralls
script:
    - tox
after_success:
    - coveralls
